[package]
name = "fnmatch-sys"
version = "1.0.0"
authors = ["Ian Wahbe <ian@wahbe.com>"]
edition = "2018"
links = "fnmatch"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cc = "1.0"
